### ISSUE TITLE
support for URL

### ISSUE THREAD

**Issue by chekanov** [decibelcooper/proio#140]
We need a support for URL for  proio/java-proio/src/main/java/proio/Reader.java 
(I've implemented it in my version of this class). It should look as this:

```
import java.net.*;

.....



 public Reader(String filename) throws IOException {


     // first URL
     if (filename.startsWith("http") || filename.startsWith("ftp")) {
                                URL url = null;
                                try {
                                        url = new URL(filename);
                                } catch (MalformedURLException e) {
                                        System.out.println("Error in accessing the URL="
                                                        + url.toString());
                                }
                               try {
                                        // System.out.println("Reading from URL: " + file);
                                        URLConnection urlConn = url.openConnection();
                                        urlConn.setDoInput(true);
                                        urlConn.setUseCaches(false);
                                        InputStream inStream = urlConn.getInputStream();
                                        stream = CodedInputStream.newInstance(inStream);
                                } catch (MalformedURLException e) {
                                        System.out.println(e.toString());
                                } catch (IOException e) {
                                        System.out.println(e.toString());
                                }

    } else {

    // normal file
    fileStream = new FileInputStream(filename);
    stream = CodedInputStream.newInstance(fileStream);

    }

  }


```

**Comment by decibelcooper** [comment]
Hi Sergei (@chekanov).  Thanks for this.  In a way, this is already supported without any ProIO modification.  Please note https://github.com/decibelcooper/proio/blob/fe37685f27320bad0a3738b5a927a6c92eb510bf/java-proio/src/main/java/proio/Reader.java#L32.

At this time I believe it is reasonable to expect the tool, not the library, to create input streams that are not simple file nodes.  The constructor at https://github.com/decibelcooper/proio/blob/fe37685f27320bad0a3738b5a927a6c92eb510bf/java-proio/src/main/java/proio/Reader.java#L27 is effectively a convenience function.

So I suggest that tools like "Info" should perform the checks that are particular to the tool in order to determine what implementation of `InputStream` should be used.

**Comment by chekanov** [comment]
Hi, David

 Ok, thanks. This looks reasonable. I'll create a new class FileMC that will take URL and will use the Reader class. All other classes, such as "Info" will use FileMC class

best, Sergei

**Comment by decibelcooper** [comment]
@chekanov, excellent!
